version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  app:
    image: hw12:0.0.1
    container_name: "hw"
    ports:
    - 8080:8080
    depends_on:
      - mongodb