version: "3"
services:
  mongodb:
    build: ./mongo
    container_name: "mongodb"
    ports:
      - 27017:27017
  app:
    build: .
    container_name: "hw"
    ports:
    - 8080:8080
    depends_on:
      - mongodb